apiVersion: litmuschaos.io/v1alpha1
kind: ChaosEngine
metadata:
  name: dns-pod-delete
  namespace: litmus
spec:
  appinfo:
    appns: default
    applabel: "app=dns-pod"
    appkind: deployment
  chaosServiceAccount: litmus-admin
  experiments:
    - name: pod-delete
      spec:
        components:
          env:
            - name: TOTAL_CHAOS_DURATION
              value: "10"
            - name: FORCE
              value: "true"
