apiVersion: v1
kind: Pod
metadata:
  name: dns-pod-1
  labels:
    app: dns
spec:
  containers:
  - name: coredns
    image: coredns/coredns:latest
    ports:
    - containerPort: 53
      protocol: UDP
